services:
  backend:
    build: ./server
    ports:
      - '5001:5001'
    volumes:
      - ./server:/backend
      - /backend/node_modules
    env_file:
      - ./server/.env
    environment:
      AI_SERVICE_URL: http://microservice:8000
    depends_on:
      - microservice
    container_name: luxeai-back
  frontend:
    build: ./client
    ports:
      - '5173:5173'
    volumes:
      - ./client/src:/frontend/src
    env_file:
      - ./client/.env
    container_name: luxeai-front
    stdin_open: true
    tty: true
    depends_on:
      - backend
  microservice:
    build: ./ai-service
    ports:
      - '8000:8000'
    container_name: luxeai-microservice
    volumes:
      - ./ai-service/src:/app/src
    command: fastapi dev src/main.py --host 0.0.0.0
