###GET ALL PRODUCTS
GET http://localhost:3000/api/products/

### GET PRODUCT POR ID
GET http://localhost:3000/api/products/1

### AGREGAR NUEVO PRODUCTO
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Goated pre",
  "price": 6969,
  "description": "PR on everything",
  "stock": 2,
  "imageUrl": "https://res.cloudinary.com/dvhcop5zx/image/upload/v1776192092/Bold_pre-workout_supplement_packaging_close-up_aiycxg.png" 
}

### ACTUALIZAR PRODUCT
PATCH  http://localhost:3000/api/products/69ddef94ce91fa9868b7d000
Content-Type: application/json 

{
  "price": 69
}


### DELETE PRODUCT
DELETE http://localhost:3000/api/products/


### REGISTRAR
POST http://localhost:3000/api/auth/register
Content-Type: application/json 

{
  "name": "Teo",
  "email": "teo@gmail.com",
  "password": "backy2026"
}

### LOGIN 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "will@hotmail.com",
  "password": "houston2027"
}
