###GET ALL PRODUCTS
GET http://localhost:3000/api/products/

### GET PRODUCT POR ID
GET http://localhost:3000/api/products/1

### AGREGAR NUEVO PRODUCTO
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Low cortisol enjoyer",
  "price": 274,
  "description": "Huge ass teddy bear to reduce your cortisol levels",
  "stock": 9,
  "imageUrl": "https://res.cloudinary.com/dvhcop5zx/image/upload/v1776231724/Giant_teddy_bear_low_cortisol_ctc34t.png" 
}

### ACTUALIZAR PRODUCT
PATCH  http://localhost:3000/api/products/69df2572665656011ca8f803
Content-Type: application/json 

{
  "imageUrl": "https://res.cloudinary.com/dvhcop5zx/image/upload/v1776232035/ChatGPT_Image_Apr_15_2026_12_46_58_AM_vjfcam.png"
}


### DELETE PRODUCT
DELETE http://localhost:3000/api/products/


### REGISTRAR
POST http://localhost:3000/api/auth/register
Content-Type: application/json 

{
  "name": "Teo",
  "email": "teo@gmail.com",
  "password": "backy2026"
}

### LOGIN 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "will@hotmail.com",
  "password": "houston2027"
}

### ADD PRODUCT TO CART

POST http://localhost:3000/api/cart/addToCart
Content-Type: application/json 

{
  "userId" : "69d59b8b40c16f068bed7e58",
  "productId": "69ddef94ce91fa9868b7d000",
  "quantity": 1
}

### GET CART
GET http://localhost:3000/api/cart/getCart/69d59b8b40c16f068bed7e58

###UPDATE CART
PATCH http://localhost:3000/api/cart/updateCart/69d59b8b40c16f068bed7e58
Content-Type: application/json

{
  "userId": "69d59b8b40c16f068bed7e58",
  "productId": "69ddef94ce91fa9868b7d000",
  "quantity": -1
}

###DELETE PRODUCT FROM CART
DELETE http://localhost:3000/api/cart/deleteProduct/69d59b8b40c16f068bed7e58/69ddef94ce91fa9868b7d000

###GET CART TOTAL
GET http://localhost:3000/api/cart/total/69d59b8b40c16f068bed7e58

###CLEAR CART
DELETE http://localhost:3000/api/cart/clearCart/69d59b8b40c16f068bed7e58